# Generated by Django 6.0.3 on 2026-03-22 08:28

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Birthday Candles', 'Message Card', 'Gift Box'",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 for free addons",
                        max_digits=10,
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, help_text="Mark as free addon"),
                ),
                ("image", models.ImageField(blank=True, upload_to="addons/")),
                (
                    "max_quantity",
                    models.IntegerField(
                        default=5, help_text="Maximum quantity per order"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Addon",
                "verbose_name_plural": "Product Addons",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Flavor', 'Frosting Type', 'Shape'",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Customer must select an option"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Attribute",
                "verbose_name_plural": "Product Attributes",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="categories/")),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Lucide icon name", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="products/")),
                ("image_2", models.ImageField(blank=True, upload_to="products/")),
                ("image_3", models.ImageField(blank=True, upload_to="products/")),
                ("image_4", models.ImageField(blank=True, upload_to="products/")),
                ("stock_quantity", models.IntegerField(default=0)),
                ("min_order_quantity", models.IntegerField(default=1)),
                ("max_order_quantity", models.IntegerField(default=10)),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "serving_size",
                    models.CharField(
                        blank=True, help_text="e.g., 'Serves 10-12'", max_length=50
                    ),
                ),
                (
                    "enable_custom_message",
                    models.BooleanField(
                        default=True, help_text="Allow custom message on cake"
                    ),
                ),
                (
                    "max_message_length",
                    models.IntegerField(
                        default=50, help_text="Maximum characters for cake message"
                    ),
                ),
                (
                    "min_lead_time",
                    models.IntegerField(
                        default=24, help_text="Minimum hours before delivery"
                    ),
                ),
                (
                    "max_lead_time",
                    models.IntegerField(
                        default=72, help_text="Maximum hours for advance order"
                    ),
                ),
                ("average_rating", models.FloatField(default=0)),
                ("review_count", models.IntegerField(default=0)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, upload_to="products/social/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Available addons for this product",
                        to="products.productaddon",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mappings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Mapping",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                through="products.ProductAttributeMapping",
                to="products.productattribute",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Chocolate', 'Vanilla', 'Red Velvet'",
                        max_length=100,
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional cost for this option",
                        max_digits=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.productattribute",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="productattributemapping",
            name="available_options",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty for all options",
                to="products.productattributeoption",
            ),
        ),
        migrations.AddField(
            model_name="productattributemapping",
            name="default_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="products.productattributeoption",
            ),
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=200)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField()),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Small', 'Medium', 'Large'", max_length=100
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="e.g., '1kg', '2kg'", max_length=50
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price adjustment from base price",
                        max_digits=10,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "price_adjustment"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_available"],
                name="products_pr_is_feat_ce1607_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattributemapping",
            unique_together={("product", "attribute")},
        ),
    ]
