# Generated by Django 6.0.3 on 2026-03-22 08:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="cards/")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., cake, star, gift)",
                        max_length=100,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=200)),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("hover-lift", "Lift on Hover"),
                            ("hover-scale", "Scale on Hover"),
                            ("hover-glow", "Glow on Hover"),
                            ("pulse", "Pulsing"),
                            ("float", "Floating"),
                            ("none", "No Animation"),
                        ],
                        default="hover-lift",
                        max_length=20,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=30),
                ),
                ("text_color", models.CharField(default="#1A1A1A", max_length=30)),
                ("border_color", models.CharField(default="#E5E7EB", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("show_on_homepage", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Featured Card",
                "verbose_name_plural": "Featured Cards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "background_type",
                    models.CharField(
                        choices=[
                            ("image", "Background Image"),
                            ("video", "Background Video"),
                            ("gradient", "Gradient"),
                            ("slider", "Image Slider"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("background_image", models.ImageField(blank=True, upload_to="hero/")),
                ("background_video", models.FileField(blank=True, upload_to="hero/")),
                ("gradient_start", models.CharField(default="#1A1A1A", max_length=20)),
                ("gradient_end", models.CharField(default="#2D2D2D", max_length=20)),
                ("slider_images", models.JSONField(blank=True, default=list)),
                (
                    "slider_interval",
                    models.IntegerField(
                        default=5000, help_text="Slider interval in milliseconds"
                    ),
                ),
                (
                    "title_animation",
                    models.CharField(
                        choices=[
                            ("fade", "Fade In"),
                            ("slide", "Slide Up"),
                            ("zoom", "Zoom In"),
                            ("typewriter", "Typewriter"),
                            ("none", "No Animation"),
                        ],
                        default="fade",
                        max_length=20,
                    ),
                ),
                (
                    "content_animation",
                    models.CharField(
                        choices=[
                            ("fade", "Fade In"),
                            ("slide", "Slide Up"),
                            ("zoom", "Zoom In"),
                            ("typewriter", "Typewriter"),
                            ("none", "No Animation"),
                        ],
                        default="slide",
                        max_length=20,
                    ),
                ),
                (
                    "animation_delay",
                    models.IntegerField(
                        default=200, help_text="Animation delay in milliseconds"
                    ),
                ),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.CharField(blank=True, max_length=200)),
                (
                    "cta_style",
                    models.CharField(
                        default="bg-gold text-charcoal hover:bg-gold/90", max_length=50
                    ),
                ),
                ("secondary_cta_text", models.CharField(blank=True, max_length=100)),
                ("secondary_cta_link", models.CharField(blank=True, max_length=200)),
                ("show_overlay", models.BooleanField(default=True)),
                (
                    "overlay_opacity",
                    models.IntegerField(
                        default=40, help_text="Overlay opacity percentage (0-100)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("is_published", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Everest Cakes", max_length=100),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        default="Bespoke, artisanal cakes for every occasion in Thika.",
                    ),
                ),
                ("site_logo", models.ImageField(blank=True, upload_to="settings/")),
                ("favicon", models.ImageField(blank=True, upload_to="settings/")),
                (
                    "phone_primary",
                    models.CharField(default="+254700000000", max_length=15),
                ),
                ("phone_secondary", models.CharField(blank=True, max_length=15)),
                (
                    "email",
                    models.EmailField(
                        default="hello@everestcakes.co.ke", max_length=254
                    ),
                ),
                ("address", models.TextField(default="Thika, Kenya")),
                (
                    "whatsapp_number",
                    models.CharField(default="+254700000000", max_length=15),
                ),
                (
                    "monday_friday",
                    models.CharField(default="8:00 AM - 7:00 PM", max_length=50),
                ),
                (
                    "saturday",
                    models.CharField(default="8:00 AM - 7:00 PM", max_length=50),
                ),
                (
                    "sunday",
                    models.CharField(default="10:00 AM - 4:00 PM", max_length=50),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "free_delivery_threshold",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=300, max_digits=10),
                ),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "customer_photo",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                ("rating", models.IntegerField(default=5)),
                ("comment", models.TextField()),
                (
                    "occasion",
                    models.CharField(
                        blank=True, help_text="e.g., Wedding, Birthday", max_length=100
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?254[0-9]{9}$",
                                message="Enter a valid Kenyan phone number",
                            )
                        ],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("newsletter_subscribed", models.BooleanField(default=True)),
                ("receive_promotions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
