# Generated by Django 6.0.3 on 2026-03-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_herosection_linked_category"),
        ("core", "0002_sitesetting_threads_url"),
    ]

    operations = []
