# Generated by Django 6.0.3 on 2026-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20260322_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hero_image",
            field=models.ImageField(blank=True, upload_to="pages/"),
        ),
        migrations.AddField(
            model_name="page",
            name="hero_image_alt",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
